name: appo
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.3
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.4.4
  freezed: ^2.4.5
  freezed_annotation: ^2.4.1
  go_router: ^7.1.1
  guarded_go_router:
    git:
      url: https://github.com/harkairt/guarded_go_router
      ref: 848542319f522fe007e38cccd8b1a9c243ca9fe9
  hooks_riverpod: ^2.4.4
  l10n:
    path: ../packages/l10n
  plugger: ^0.0.1
  riverpod: ^2.4.4
  riverpod_annotation: ^2.2.1
  sentry_flutter: ^7.10.1
  stack_trace: ^1.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  custom_lint: ^0.5.4
  riverpod_lint: ^2.3.1
  riverpod_generator: ^2.3.4

flutter:
  uses-material-design: true
